---
- hosts: all
  gather_facts: yes
  become: yes
  name: Upgrade software
  tasks:
    # Use a block to perform tasks conditionally—only if running Ubuntu 16.04.
    - block:

      - debug:
          msg: 'This server is running Ubuntu 16.04 LTS and will be upgraded to 18.04 LTS.'

      # Now would be a good time to take a backup if you can trigger an
      # automated backup!

      - name: Remove the EOL message of the day if one exists.
        file:
          path: "{{ item }}"
          state: absent
        with_items:
          - /etc/update-motd.d/99-esm
          - /run/motd.dynamic

      - name: Upgrade all packages to the latest version
        apt: update_cache=yes upgrade=full

      - name: Ensure update-manager-core is installed.
        apt: name=update-manager-core state=present

      - name: Run do-release-upgrade non-interactively.
        command: do-release-upgrade -m server -f DistUpgradeViewNonInteractive
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- import_playbook: ceph_rolling_reboot.yml
